// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, Fragment, jsxs } from 'react/jsx-runtime';
import { useEffect, Fragment as Fragment_9e46adc109100050462083db825547fcdce28feb } from 'react';
import * as React from 'react';
import { cn } from 'lib/utils';
import { Placeholder, CdpHelper, useSitecore } from '@sitecore-content-sdk/nextjs';
import Head from 'next/head';
import client from 'lib/sitecore-client';
import Image from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-content-sdk/events';
import config from 'sitecore.config';
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from 'components/ui/breadcrumb';
import { getDatasource, getFieldValue } from 'lib/component-props';
import { NoDataFallback } from 'utils/NoDataFallback';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'Fragment', value: Fragment },
      { name: 'jsxs', value: jsxs },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useEffect', value: useEffect },
      { name: 'Fragment', value: Fragment_9e46adc109100050462083db825547fcdce28feb },
      { name: '*', value: React },
    ]
  },
  {
    module: 'lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Placeholder', value: Placeholder },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'useSitecore', value: useSitecore },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: 'components/ui/breadcrumb',
    exports: [
      { name: 'Breadcrumb', value: Breadcrumb },
      { name: 'BreadcrumbItem', value: BreadcrumbItem },
      { name: 'BreadcrumbLink', value: BreadcrumbLink },
      { name: 'BreadcrumbList', value: BreadcrumbList },
      { name: 'BreadcrumbPage', value: BreadcrumbPage },
      { name: 'BreadcrumbSeparator', value: BreadcrumbSeparator },
    ]
  },
  {
    module: 'lib/component-props',
    exports: [
      { name: 'getDatasource', value: getDatasource },
      { name: 'getFieldValue', value: getFieldValue },
    ]
  },
  {
    module: 'utils/NoDataFallback',
    exports: [
      { name: 'NoDataFallback', value: NoDataFallback },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
