/**
 * Placeholder. At build/serve time, Angular's fileReplacements swaps this for
 * environment.dev.ts (development) or environment.prod.ts (production).
 * Those files are generated by `npm run gen:env:dev` or `npm run gen:env:prod`.
 */
export const environment = {};
