/**
 * Generates src/environments/environment.dev.ts or environment.prod.ts
 * from `.env` files (via dotenv). Only variables whose names start with `CSDK_PUBLIC_`
 * are written into the file so the browser bundle does not embed server-only secrets.
 *
 * Server-side code reads full configuration from `process.env` at runtime
 * (see `defineConfig` in `@sitecore-content-sdk/angular` and `load-env.ts` / `server.ts`).
 *
 * Usage:
 *   tsx scripts/generate-environment.ts --dev   (loads .env then .env.dev)
 *   tsx scripts/generate-environment.ts --prod  (loads .env then .env.prod)
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import dotenv from 'dotenv';

const projectRoot = process.cwd();
const angularEnvDir = resolve(projectRoot, 'src', 'environments');

function loadEnvFiles(mode: 'dev' | 'prod'): void {
  const contextEnvFile = mode === 'dev' ? '.env.dev' : '.env.prod';

  const baseEnvPath = resolve(projectRoot, '.env');
  const localEnvPath = resolve(projectRoot, '.env.local');
  const contextEnvPath = resolve(projectRoot, contextEnvFile);
  dotenv.config({ path: [baseEnvPath, localEnvPath, contextEnvPath] });
}

function serialize(production: boolean): string {
  const lines: string[] = [`  production: '${production}',`] 

  const keys = Object.keys(process.env).sort();
  for (const key of keys) {
    if (!key.startsWith('CSDK_PUBLIC_')) {
      continue;
    }
    const value = process.env[key] ?? '';
    lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(value)},`);
  }

  return `\
/**
 * Auto-generated by scripts/generate-environment.ts — do not edit.
 * Mode: ${production ? 'production' : 'development'}
 *
 * Includes the production flag and CSDK_PUBLIC_* keys (browser-safe).
 * NODE_ENV and other server values come from process.env at runtime (see load-env.ts + defineConfig).
 */
export const environment = {
${lines.join('\n')}
};
`;
}

function parseMode(): 'dev' | 'prod' {
  const args = process.argv.slice(2);
  if (args.includes('--dev')) return 'dev';
  if (args.includes('--prod')) return 'prod';
  console.error('Usage: tsx scripts/generate-environment.ts --dev | --prod');
  process.exit(1);
}

function main(): void {
  const mode = parseMode();
  loadEnvFiles(mode);

  const production = mode === 'prod';
  const outFile = production ? 'environment.prod.ts' : 'environment.dev.ts';
  const outPath = resolve(angularEnvDir, outFile);
  writeFileSync(outPath, serialize(production), 'utf8');
  console.log(`[content-sdk:prebuild] Wrote ${outFile} (mode=${mode})`);
}

main();
